/**/controller_manager:
  ros__parameters:
    update_rate: 500  # Update rate in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    torque_passthrough_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_ramped_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_passthrough_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController

    position_trajectory_controller:
      type: forward_command_controller/ForwardCommandController
      
    position_filtered_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController

    position_passthrough_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController

    position_pid_controller:
      type: pid_controller/PidController

    velocity_pid_controller:
      type: pid_controller/PidController

    odrive_pid_controller:
      type: odrive_pid_controller/ODrivePidController

/**/torque_passthrough_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
    interface_name: effort

/**/velocity_ramped_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
    interface_name: velocity

/**/velocity_passthrough_controller:
  ros__parameters:
    joint: $(var tf_prefix)joint_1
    interface_names: 
     - velocity
     - effort

/**/position_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
    interface_name: position

/**/position_filtered_controller:
  ros__parameters:
    joint: $(var tf_prefix)joint_1
    interface_names: 
     - position
     - velocity

/**/position_passthrough_controller:
  ros__parameters:
    joint: $(var tf_prefix)joint_1
    interface_names: 
     - position
     - velocity
     - effort

# Outer PID Loop: Position PID Controller
position_pid_controller:
  ros__parameters:
    dof_names:
      - velocity_pid_controller/$(var tf_prefix)joint_1
    command_interface: velocity
    reference_and_state_interfaces:
      - position
    reference_and_state_dof_names:
      - $(var tf_prefix)joint_1
    set_current_state_as_first_setpoint: true
    gains:
      "velocity_pid_controller/$(var tf_prefix)joint_1":
        p: 30.0
        i: 0.0
        d: 0.0
        u_clamp_max: 50.0   
        u_clamp_min: -50.0
        antiwindup_strategy: "none"

# Inner PID Loop: Velocity PID Controller
velocity_pid_controller:
  ros__parameters:
    dof_names:
      - $(var tf_prefix)joint_1
    command_interface: effort
    reference_and_state_interfaces:
      - velocity
    set_current_state_as_first_setpoint: true
    gains:
      $(var tf_prefix)joint_1:
        p: 0.03
        i: 0.6
        d: 0.0
        u_clamp_max: 40.0  # Limits maximum effort/torque sent to the hardware (Nm or N)
        u_clamp_min: -40.0
        antiwindup_strategy: "none"

# Custom Controller
odrive_pid_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
    gains:
      $(var tf_prefix)joint_1:
        position: {"p": 10.0, "i": 0.0, "d": 0.0, "min_output": -50.0, "max_output": 50.0}
        velocity: {"p": 0.03, "i": 0.6, "d": 0.0, "min_output": -.inf, "max_output": .inf}
