#ifndef ODRIVE_PID_CONTROLLER__ODRIVE_PID_CONTROLLER_HPP_
#define ODRIVE_PID_CONTROLLER__ODRIVE_PID_CONTROLLER_HPP_

#include "controller_interface/controller_interface.hpp"
#include "control_toolbox/pid.hpp"
#include "control_msgs/msg/multi_dof_command.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
// auto-generated by generate_parameter_library
#include "odrive_pid_controller/odrive_pid_controller_parameters.hpp"

namespace odrive_pid_controller
{
using MultiDOFCommand = control_msgs::msg::MultiDOFCommand;
class ODrivePidController : public controller_interface::ControllerInterface
{
  struct Joint {
    // Constructor
    explicit Joint(const std::string & joint_name, const odrive_pid_controller::Params::Gains::MapJoints & joint_gains);
    // Parameters
    std::string name;
    double position_reference = std::numeric_limits<double>::quiet_NaN();
    // PIDs
    std::shared_ptr<control_toolbox::Pid> velocity_pid;
    std::shared_ptr<control_toolbox::Pid> position_pid;
    // State Interfaces
    const hardware_interface::LoanedStateInterface* position_state_handle = nullptr;
    const hardware_interface::LoanedStateInterface* velocity_state_handle = nullptr;
    // Command Interfaces
    hardware_interface::LoanedCommandInterface* effort_cmd_handle = nullptr;
  };
public:
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::shared_ptr<ParamListener> param_listener;
  Params params;
  // Joint
  std::vector<Joint> joints;
  // Listener
  realtime_tools::RealtimeThreadSafeBox<MultiDOFCommand> rt_buffer;
  rclcpp::Subscription<MultiDOFCommand>::SharedPtr joints_cmd_sub;
  // helper functions
  void get_latest_references();
};

}  // namespace odrive_pid_controller

#endif  // ODRIVE_PID_CONTROLLER__ODRIVE_PID_CONTROLLER_HPP_
